services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: wheelHub_app
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
    command: bash -c "npm install && apache2-foreground"
    env_file:
      - .env
    depends_on:
      - dataBase

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: wheelHub_api
    ports:
      - '8000:80'
    volumes:
      - ./api:/var/www/html
    command: bash -c "composer install && apache2-foreground"
    depends_on:
      - dataBase

  dataBase:
    image: mysql:latest
    container_name: wheelHub_db
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d

networks:
  wheelHub_network:
    driver: bridge

volumes:
  db_data:
