# Używamy oficjalnego obrazu MySQL
FROM mysql:8.0

# Ustawiamy domyślne zmienne środowiskowe
ENV MYSQL_DATABASE=wheel_db
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_USER=wheel_user
ENV MYSQL_PASSWORD=user_password

# Otwarcie portu dla MySQL
EXPOSE 3306